# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtGui import QPalette,QBrush,QPixmap,QIcon
from PyQt5 import QtCore, QtGui, QtWidgets
import qtawesome
import os


class ABOUT(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 400)
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(170, 20, 256, 41))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 80, 111, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 150, 111, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(40, 380, 91, 16))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(500, 360, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(140, 60, 641, 91))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(140, 140, 421, 61))
        self.label_5.setObjectName("label_5")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(0, 60, 601, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(0, 200, 601, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(30, 210, 551, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(220, 240, 150, 150))
        self.label_7.setText("")
        path = os.path.join('tools', "wt.png")
        self.label_7.setPixmap(QtGui.QPixmap(path))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")

        self.pushButton.clicked.connect(Form.close)
        self.beautify(Form)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffaa00;\">关注我们</span></p></body></html>"))
        self.label.setText(_translate("Form", "彩妆迁移是什么"))
        self.label_2.setText(_translate("Form", "价值观和愿景"))
        self.label_3.setText(_translate("Form", "©2020kviTRS"))
        self.pushButton.setText(_translate("Form", "返回"))
        self.label_4.setText(_translate("Form", "在彩妆迁移应用系统中，输入一张无妆图像，选择一张有妆图像，\n"
"则可以将有妆图片的妆容迁移到未化妆的图片上去，同时，无妆\n"
"图像原有的面部特征得到保留。"))
        self.label_5.setText(_translate("Form", "使用户不需要耗费时间学习化妆技巧以及花钱购买化妆品，可以\n"
"在软件上在线试妆轻松找到适合自己的产品。使商家更轻松地销\n"
"售自己的产品。"))
        self.label_6.setText(_translate("Form", "如果您对我们有什么好的建议或是希望与我们交流彩妆迁移技术，请联系我们。"))

    def beautify(self,Form):
        Form.setWindowOpacity(0.95)
        palette = QPalette()
        path = os.path.join('tools', 'win.jpg')
        palette.setBrush(QPalette.Background, QBrush(QPixmap(path)))
        Form.setPalette(palette)

        # icon
        iconpath = os.path.join('tools', 'amg.jpg')
        Form.setWindowIcon(QIcon(iconpath))

        spin_icon = qtawesome.icon('fa5s.ban', color='black')
        self.pushButton.setIcon(spin_icon)

        # 设置pushbutton格式
        self.pushButton.setStyleSheet('''QPushButton{border:none;}
                                QPushButton:hover{color:white;
                                            border:2px solid #F3F3F5;
                                            border-radius:35px;
                                            background:darkGray;}''')
