# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choose.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from ui.mkup import *
from ui.transfer import *
from PyQt5.QtGui import QPalette,QBrush,QPixmap,QIcon
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import *
import qtawesome
import os


class CHOOSE(object):
    def setupUi(self, Form, product, name):
        self.product=product   #product-->string   productname
        self.name=name
        Form.setObjectName("Form")
        Form.resize(600, 400)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(470, 110, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(470, 220, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(80, 30, 300, 300))
        self.label.setText("")
        self.label.setScaledContents(True)
        path=os.path.join('tools/makeup_show', self.product)
        self.label.setPixmap(QtGui.QPixmap(path))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(150, 350, 200, 15))
        self.label_2.setObjectName("label_2")

        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(440, 0, 16, 401))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.transfer = Transferx()
        self.transfer.set(product)
        self.pushButton.clicked.connect(self.transfer.show)

        self.pushButton_2.clicked.connect(Form.close)
        self.beautify(Form)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "开始试妆"))
        self.pushButton_2.setText(_translate("Form", "返回"))
        self.label_2.setText(_translate("Form", self.name))

    def beautify(self,Form):
        # 利用qtawesome设置图标
        Form.setWindowOpacity(0.95)
        palette = QPalette()
        path = os.path.join('tools', 'win.jpg')
        palette.setBrush(QPalette.Background, QBrush(QPixmap(path)))
        Form.setPalette(palette)

        # icon
        iconpath = os.path.join('tools', 'amg.jpg')
        Form.setWindowIcon(QIcon(iconpath))

        spin_icon = qtawesome.icon('fa5s.ban', color='black')
        self.pushButton_2.setIcon(spin_icon)

        spin_icon2 = qtawesome.icon('fa.comment', color='black')
        self.pushButton.setIcon(spin_icon2)

        # 设置pushbutton格式
        self.pushButton.setStyleSheet('''QPushButton{border:none;}
                                QPushButton:hover{color:white;
                                            border:2px solid #F3F3F5;
                                            border-radius:35px;
                                            background:darkGray;}''')
        self.pushButton_2.setStyleSheet('''QPushButton{border:none;}
                                        QPushButton:hover{color:white;
                                                    border:2px solid #F3F3F5;
                                                    border-radius:35px;
                                                    background:darkGray;}''')