# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from ui.transfer import *
from ui.helpwindow import *
from ui.about import *
from ui.set import *
from ui.choose import *
from PyQt5.QtCore import *
from PyQt5.QtGui import QPalette,QBrush,QPixmap,QIcon
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import *
import qtawesome
import os

class mainfunc(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 400)
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(120, 0, 20, 401))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(20, 30, 91, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 120, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 170, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 220, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(170, 60, 72, 15))
        self.label_2.setObjectName("label_2")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 360, 93, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(400, 50, 72, 15))
        self.label_3.setObjectName("label_3")
        self.toolButton_3 = QtWidgets.QToolButton(Form)
        self.toolButton_3.setGeometry(QtCore.QRect(270, 70, 150, 160))
        icon = QtGui.QIcon()
        path = os.path.join('tools/makeup_show', "06flame.PNG")
        icon.addPixmap(QtGui.QPixmap(path), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon)
        self.toolButton_3.setIconSize(QtCore.QSize(150, 140))
        self.toolButton_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_3.setObjectName("toolButton_3")
        self.toolButton_4 = QtWidgets.QToolButton(Form)
        self.toolButton_4.setGeometry(QtCore.QRect(440, 70, 150, 160))
        icon1 = QtGui.QIcon()
        path1=os.path.join('tools/makeup_show', '07rubyrush.PNG')
        icon1.addPixmap(QtGui.QPixmap(path1), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_4.setIcon(icon1)
        self.toolButton_4.setIconSize(QtCore.QSize(150, 140))
        self.toolButton_4.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_4.setObjectName("toolButton_4")
        self.toolButton_5 = QtWidgets.QToolButton(Form)
        self.toolButton_5.setGeometry(QtCore.QRect(440, 230, 150, 160))
        icon2 = QtGui.QIcon()
        path2 = os.path.join('tools/makeup_show', "16scarletrouge.PNG")
        icon2.addPixmap(QtGui.QPixmap(path2), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_5.setIcon(icon2)
        self.toolButton_5.setIconSize(QtCore.QSize(140, 140))
        self.toolButton_5.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_5.setObjectName("toolButton_5")
        self.toolButton_6 = QtWidgets.QToolButton(Form)
        self.toolButton_6.setGeometry(QtCore.QRect(270, 230, 150, 160))
        icon3 = QtGui.QIcon()
        path3 = os.path.join('tools/makeup_show', "09truecoral.PNG")
        icon3.addPixmap(QtGui.QPixmap(path3), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_6.setIcon(icon3)
        self.toolButton_6.setIconSize(QtCore.QSize(140, 140))
        self.toolButton_6.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_6.setObjectName("toolButton_6")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(140, 90, 111, 28))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(140, 140, 111, 28))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(140, 240, 111, 28))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(140, 190, 111, 28))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        self.pushButton_10.setGeometry(QtCore.QRect(140, 290, 111, 28))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(Form)
        self.pushButton_11.setGeometry(QtCore.QRect(140, 340, 111, 28))
        self.pushButton_11.setObjectName("pushButton_11")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(250, 40, 20, 361))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(130, 30, 471, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(140, 10, 381, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_12 = QtWidgets.QPushButton(Form)
        self.pushButton_12.setGeometry(QtCore.QRect(530, 10, 61, 28))
        self.pushButton_12.setObjectName("pushButton_12")

        self.pushButton_5.clicked.connect(QCoreApplication.quit)

        self.helpfunc = QWidget()
        self.helpx = HELPFUNC()
        self.helpx.setupUi(self.helpfunc)
        self.pushButton_3.clicked.connect(self.helpfunc.show)

        self.transfer = MakeupTransfer()
        self.pushButton_2.clicked.connect(self.transfer.show)

        self.aboutfunc = QWidget()
        self.about = ABOUT()
        self.about.setupUi(self.aboutfunc)
        self.pushButton_4.clicked.connect(self.aboutfunc.show)

        self.setfunc = QWidget()
        self.sx = SETS()
        self.sx.setupUi(self.setfunc)
        self.pushButton.clicked.connect(self.setfunc.show)

        self.choosefunc = QWidget()
        self.ch = CHOOSE()
        self.ch.setupUi(self.choosefunc,"06flame.PNG","Tom Ford 06 flame")
        self.toolButton_3.clicked.connect(self.choosefunc.show)

        self.choosefunc1 = QWidget()
        self.ch1 = CHOOSE()
        self.ch1.setupUi(self.choosefunc1, '07rubyrush.PNG',"Tom Ford 07 ruby rush")
        self.toolButton_4.clicked.connect(self.choosefunc1.show)

        self.choosefunc2 = QWidget()
        self.ch2 = CHOOSE()
        self.ch2.setupUi(self.choosefunc2, "16scarletrouge.PNG","Tom Ford 16 scarlet rouge")
        self.toolButton_5.clicked.connect(self.choosefunc2.show)

        self.choosefunc3 = QWidget()
        self.ch3 = CHOOSE()
        self.ch3.setupUi(self.choosefunc3, "09truecoral.PNG","Tom Ford 09 true coral")
        self.toolButton_6.clicked.connect(self.choosefunc3.show)

        self.choosefunc4 = QWidget()
        self.ch4 = CHOOSE()
        self.ch4.setupUi(self.choosefunc4, "08VELVETCHERRY.png", "Tom Ford 08 velvet cherry")
        self.pushButton_6.clicked.connect(self.choosefunc4.show)

        self.choosefunc5 = QWidget()
        self.ch5 = CHOOSE()
        self.ch5.setupUi(self.choosefunc5, "15LAWOMAN.png", "Tom Ford 15 LAwoman")
        self.pushButton_7.clicked.connect(self.choosefunc5.show)

        self.choosefunc6 = QWidget()
        self.ch6 = CHOOSE()
        self.ch6.setupUi(self.choosefunc6, "19STILETTO.png", "Tom Ford 19 stiletto")
        self.pushButton_8.clicked.connect(self.choosefunc6.show)

        self.choosefunc7 = QWidget()
        self.ch7 = CHOOSE()
        self.ch7.setupUi(self.choosefunc7, "24MAROCAIN.png", "Tom Ford 24 MAROCAIN")
        self.pushButton_9.clicked.connect(self.choosefunc7.show)

        self.choosefunc8 = QWidget()
        self.ch8 = CHOOSE()
        self.ch8.setupUi(self.choosefunc8, "27SHAMELESS.png", "Tom Ford 27 SHAMELESS")
        self.pushButton_10.clicked.connect(self.choosefunc8.show)

        self.choosefunc9 = QWidget()
        self.ch9 = CHOOSE()
        self.ch9.setupUi(self.choosefunc9, "29MARABOU.png", "Tom Ford 29 MARABOU")
        self.pushButton_11.clicked.connect(self.choosefunc9.show)

        self.retranslateUi(Form)
        self.beautify(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "kvi-TRS"))
        self.pushButton.setText(_translate("Form", "所有产品"))
        self.pushButton_2.setText(_translate("Form", "彩妆迁移"))
        self.pushButton_3.setText(_translate("Form", "遇到问题"))
        self.pushButton_4.setText(_translate("Form", "关注我们"))
        self.label_2.setText(_translate("Form", "最新推荐"))
        self.pushButton_5.setText(_translate("Form", "退出"))
        self.label_3.setText(_translate("Form", "热门产品"))
        self.toolButton_3.setText(_translate("Form", "TF 06 flame"))
        self.toolButton_4.setText(_translate("Form", "TF 07 ruby rush"))
        self.toolButton_5.setText(_translate("Form", "TF 16 scarletrouge"))
        self.toolButton_6.setText(_translate("Form", "TF 09 true coral"))
        self.pushButton_6.setText(_translate("Form", "TF 08"))
        self.pushButton_7.setText(_translate("Form", "TF 15"))
        self.pushButton_8.setText(_translate("Form", "TF 19"))
        self.pushButton_9.setText(_translate("Form", "TF 24"))
        self.pushButton_10.setText(_translate("Form", "TF 27"))
        self.pushButton_11.setText(_translate("Form", "TF 29"))
        self.pushButton_12.setText(_translate("Form", "搜索"))

    def beautify(self,Form):
        # 利用qtawesome设置图标
        Form.setWindowOpacity(0.95)
        palette = QPalette()
        path = os.path.join('tools', 'timg1.jpg')
        palette.setBrush(QPalette.Background, QBrush(QPixmap(path)))
        Form.setPalette(palette)

        # icon
        iconpath = os.path.join('tools', 'amg.jpg')
        Form.setWindowIcon(QIcon(iconpath))

        #spin_icon = qtawesome.icon('fa5s.microphone-alt', color='black')
        spin_icon2 = qtawesome.icon('fa.question', color='black')
        spin_icon4 = qtawesome.icon('fa.comment', color='black')
        spin_icon5 = qtawesome.icon('fa5s.ban', color='black')
        spin_icon3 = qtawesome.icon('fa.sellsy', color='black')
        spin_icon6 = qtawesome.icon('fa.book', color='black')
        self.pushButton.setIcon(spin_icon6)
        self.pushButton_2.setIcon(spin_icon3)
        self.pushButton_3.setIcon(spin_icon2)
        self.pushButton_4.setIcon(spin_icon4)
        self.pushButton_5.setIcon(spin_icon5)
        #self.pushButton_6.setIcon(spin_icon6)

        # 设置pushbutton格式
        self.pushButton.setStyleSheet('''QPushButton{border:none;}
                                QPushButton:hover{color:white;
                                            border:2px solid #F3F3F5;
                                            border-radius:35px;
                                            background:darkGray;}''')

        self.pushButton_2.setStyleSheet('''QPushButton{border:none;}
                                        QPushButton:hover{color:white;
                                                    border:2px solid #F3F3F5;
                                                    border-radius:35px;
                                                    background:darkGray;}''')

        self.pushButton_3.setStyleSheet('''QPushButton{border:none;}
                                        QPushButton:hover{color:white;
                                                    border:2px solid #F3F3F5;
                                                    border-radius:35px;
                                                    background:darkGray;}''')

        self.pushButton_4.setStyleSheet('''QPushButton{border:none;}
                                        QPushButton:hover{color:white;
                                                    border:2px solid #F3F3F5;
                                                    border-radius:35px;
                                                    background:darkGray;}''')

        self.pushButton_5.setStyleSheet('''QPushButton{border:none;}
                                        QPushButton:hover{color:white;
                                                    border:2px solid #F3F3F5;
                                                    border-radius:35px;
                                                    background:darkGray;}''')

        self.pushButton_6.setStyleSheet('''QPushButton{border:none;}
                                        QPushButton:hover{color:white;
                                                    border:2px solid #F3F3F5;
                                                    border-radius:35px;
                                                    background:darkGray;}''')

        self.pushButton_7.setStyleSheet('''QPushButton{border:none;}
                                        QPushButton:hover{color:white;
                                                    border:2px solid #F3F3F5;
                                                    border-radius:35px;
                                                    background:darkGray;}''')

        self.pushButton_8.setStyleSheet('''QPushButton{border:none;}
                                        QPushButton:hover{color:white;
                                                    border:2px solid #F3F3F5;
                                                    border-radius:35px;
                                                    background:darkGray;}''')

        self.pushButton_9.setStyleSheet('''QPushButton{border:none;}
                                        QPushButton:hover{color:white;
                                                    border:2px solid #F3F3F5;
                                                    border-radius:35px;
                                                    background:darkGray;}''')

        self.pushButton_10.setStyleSheet('''QPushButton{border:none;}
                                        QPushButton:hover{color:white;
                                                    border:2px solid #F3F3F5;
                                                    border-radius:35px;
                                                    background:darkGray;}''')

        self.pushButton_11.setStyleSheet('''QPushButton{border:none;}
                                        QPushButton:hover{color:white;
                                                    border:2px solid #F3F3F5;
                                                    border-radius:35px;
                                                    background:darkGray;}''')

        self.pushButton_12.setStyleSheet('''QPushButton{border:none;}
                                        QPushButton:hover{color:white;
                                                    border:2px solid #F3F3F5;
                                                    border-radius:35px;
                                                    background:darkGray;}''')
