# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'set.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from ui.TF import *
from PyQt5.QtGui import QPalette,QBrush,QPixmap,QIcon
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import *
import qtawesome
import os

class SETS(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 400)
        self.toolButton = QtWidgets.QToolButton(Form)
        self.toolButton.setGeometry(QtCore.QRect(40, 30, 150, 150))
        icon = QtGui.QIcon()
        path = os.path.join('tools/makeup_show', "TF.jpg")
        icon.addPixmap(QtGui.QPixmap(path), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(150, 150))
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(Form)
        self.toolButton_2.setGeometry(QtCore.QRect(250, 30, 130, 150))
        icon1 = QtGui.QIcon()
        path2 = os.path.join('tools/makeup_show', "YSL.jpg")
        icon1.addPixmap(QtGui.QPixmap(path2), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon1)
        self.toolButton_2.setIconSize(QtCore.QSize(150, 150))
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolButton_3 = QtWidgets.QToolButton(Form)
        self.toolButton_3.setGeometry(QtCore.QRect(480, 80, 47, 21))
        self.toolButton_3.setObjectName("toolButton_3")
        self.toolButton_4 = QtWidgets.QToolButton(Form)
        self.toolButton_4.setGeometry(QtCore.QRect(90, 260, 47, 21))
        self.toolButton_4.setObjectName("toolButton_4")
        self.toolButton_5 = QtWidgets.QToolButton(Form)
        self.toolButton_5.setGeometry(QtCore.QRect(290, 260, 47, 21))
        self.toolButton_5.setObjectName("toolButton_5")
        self.toolButton_6 = QtWidgets.QToolButton(Form)
        self.toolButton_6.setGeometry(QtCore.QRect(466, 260, 71, 21))
        self.toolButton_6.setObjectName("toolButton_6")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(270, 350, 93, 28))
        self.pushButton.setObjectName("pushButton")

        self.pushButton.clicked.connect(Form.close)
        self.beautify(Form)

        self.TFfunc = QWidget()
        self.TF = TFd()
        self.TF.setupUi(self.TFfunc)
        self.toolButton.clicked.connect(self.TFfunc.show)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "product"))
        self.toolButton.setText(_translate("Form", "Tom Ford 口红"))
        self.toolButton_2.setText(_translate("Form", "YSL 口红"))
        self.toolButton_3.setText(_translate("Form", "..."))
        self.toolButton_4.setText(_translate("Form", "..."))
        self.toolButton_5.setText(_translate("Form", "..."))
        self.toolButton_6.setText(_translate("Form", "敬请期待"))
        self.pushButton.setText(_translate("Form", "返回"))

    def beautify(self,Form):
        # 利用qtawesome设置图标
        Form.setWindowOpacity(0.95)
        palette = QPalette()
        path = os.path.join('tools', 'win.jpg')
        palette.setBrush(QPalette.Background, QBrush(QPixmap(path)))
        Form.setPalette(palette)

        # icon
        iconpath = os.path.join('tools', 'amg.jpg')
        Form.setWindowIcon(QIcon(iconpath))

        spin_icon = qtawesome.icon('fa5s.ban', color='black')
        self.pushButton.setIcon(spin_icon)

        # 设置pushbutton格式
        self.pushButton.setStyleSheet('''QPushButton{border:none;}
                        QPushButton:hover{color:white;
                                    border:2px solid #F3F3F5;
                                    border-radius:35px;
                                    background:darkGray;}''')